# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Margules
email: eric.i.margules@gmail.com
description: 'Desktop and web developer specializing in Ruby, Rails, JavaScript, and other technologies that take applications from "oh" to "woah!'
baseurl: ""
url: "https://ericmargules.github.io"
twitter_username: jekyllrb
github_username:  ericmargules

# Build settings
markdown: kramdown
